# Nyx — app-only R8 rules.
#
# Since SPEC_NYX_REWRITE 1b-4c (D1 end form) the rules every app needs are no longer
# written here:
#   - ACRA library rules  → :feature-crashreporting/consumer-rules.pro (consumer rules,
#     merged automatically into every app that depends on it);
#   - global options (-keepattributes SourceFile,LineNumberTable, -renamesourcefileattribute),
#     BuildConfig keep, Throwable and enum-name keeps for com.github.reygnn.nyx_launcher.** AND the
#     shared com.github.reygnn.launcher.** → generated by build-logic
#     (launcher.android.application, ReleaseRules.kt) from android.namespace.
# Libraries (Hilt, kotlinx-serialization, fragment, ACRA …) ship their own consumer rules.
# The merged result is written to app/build/outputs/mapping/release/configuration.txt —
# audit there.
#
# Add a rule here only if it is genuinely Nyx-specific. None today.
