import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure

/** Package prefix of every shared module (:core, :common-*, :feature-*), bundled into both apps. */
private const val SHARED_PACKAGE = "com.github.reygnn.launcher"

/**
 * R8 rules every app needs, generated from the app's namespace (SPEC_NYX_REWRITE D1 end
 * form). Kept out of the modules so no app can ship without them again.
 *  - Global options: readable stack traces (line numbers survive; the obfuscated source
 *    file name is mapped back by the uploaded mapping). AGP 9 rejects these in library
 *    consumer rules, so they must be app-level.
 *  - BuildConfig: read reflectively by ACRA (buildConfigClass).
 *  - Throwable names: ACRA groups reports by exception class name — for the app's own
 *    exceptions AND the shared ones (LoggedThrowable, AnrException, WatchdogStallException),
 *    which neither app kept before D1's end form.
 *  - Enum constant names: persisted by name (DataStore, backups) — app and shared enums.
 * The ACRA library rules come as consumer rules from :feature-crashreporting.
 */
internal fun appReleaseRules(namespace: String): String = buildString {
    appendLine("# Generated by build-logic (launcher.android.application) — do not edit.")
    appendLine("-keepattributes SourceFile,LineNumberTable")
    appendLine("-renamesourcefileattribute SourceFile")
    appendLine("-keep class $namespace.BuildConfig { *; }")
    for (pkg in listOf(namespace, SHARED_PACKAGE)) {
        appendLine("-keepnames class $pkg.** extends java.lang.Throwable")
        appendLine("-keepclassmembernames enum $pkg.** { <fields>; }")
    }
}

/**
 * Wires the R8 inputs of every build type: AGP's optimize defaults, the module's own
 * `proguard-rules.pro` (app-only rules) and the generated file above. Runs in
 * finalizeDsl, where the module's namespace is known.
 */
internal fun Project.configureReleaseRules() {
    val generated = layout.buildDirectory.file("generated/launcher/proguard/launcher-app-rules.pro")
    extensions.configure<ApplicationAndroidComponentsExtension> {
        finalizeDsl { android: ApplicationExtension ->
            val namespace = requireNotNull(android.namespace) { "launcher.android.application needs android.namespace" }
            val rulesFile = generated.get().asFile
            rulesFile.parentFile.mkdirs()
            rulesFile.writeText(appReleaseRules(namespace))
            android.defaultConfig.proguardFiles(
                android.getDefaultProguardFile("proguard-android-optimize.txt"),
                project.file("proguard-rules.pro"),
                rulesFile,
            )
        }
    }
}
